title: jekyll-bookworm
author:
  name: Subhodeep Sarkar
  email:
description: > # this means to ignore newlines until "show_excerpts:"
  jekyll-bookworm is a template to provide Jekyll users
  with a simple, hackable book reviews system. Contributions
  welcome!

show_excerpts: false # set to true to show excerpts on the homepage

###### comment out base url out ######

baseurl: "/jekyll-bookworm" # the subpath of your site, e.g. /blog
url: "https://subhodeeps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: astres_occlus
github_username:  subhodeeps

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # google_scholar_id: qc6CJjYAAAAJ

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
#####################################
permalink: /:categories/:title/

# Collections
collections:
    books:
        output: true
        permalink: /:collection/:title/

future: true

header_pages:
  - books.md
  - howto.md

include:
  - images

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - examples/
  - README.md
